default_platform(:ios)

platform :ios do
  desc "Deploy Beta"
  lane :beta do
    build_app(scheme: "Runner")
    upload_to_testflight
  end

  desc "Deploy Production"
  lane :production do
    build_app(scheme: "Runner")
    upload_to_app_store
  end
end
