///
/// Generated file. Do not edit.
///
// coverage:ignore-file
// ignore_for_file: type=lint, unused_import

part of 'strings.g.dart';

// Path: <root>
typedef TranslationsEn = Translations; // ignore: unused_element
class Translations implements BaseTranslations<AppLocale, Translations> {
	/// Returns the current translations of the given [context].
	///
	/// Usage:
	/// final t = Translations.of(context);
	static Translations of(BuildContext context) => InheritedLocaleData.of<AppLocale, Translations>(context).translations;

	/// You can call this constructor and build your own translation instance of this locale.
	/// Constructing via the enum [AppLocale.build] is preferred.
	Translations({Map<String, Node>? overrides, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver, TranslationMetadata<AppLocale, Translations>? meta})
		: assert(overrides == null, 'Set "translation_overrides: true" in order to enable this feature.'),
		  $meta = meta ?? TranslationMetadata(
		    locale: AppLocale.en,
		    overrides: overrides ?? {},
		    cardinalResolver: cardinalResolver,
		    ordinalResolver: ordinalResolver,
		  ) {
		$meta.setFlatMapFunction(_flatMapFunction);
	}

	/// Metadata for the translations of <en>.
	@override final TranslationMetadata<AppLocale, Translations> $meta;

	/// Access flat map
	dynamic operator[](String key) => $meta.getTranslation(key);

	late final Translations _root = this; // ignore: unused_field

	Translations $copyWith({TranslationMetadata<AppLocale, Translations>? meta}) => Translations(meta: meta ?? this.$meta);

	// Translations
	String get home => 'Home';
	String get tests => 'Tests';
	String get profile => 'Profile';
	String get welcome_message => 'Welcome to Drive Test';
	String get save => 'Save';
	String get cancel => 'Cancel';
	String get delete => 'Delete';
	String get logout => 'Logout';
	String get loading => 'Loading...';
	String get settings_title => 'Settings';
	String get settings_appearance => 'Appearance';
	String get settings_test_prefs => 'Test Preferences';
	String get settings_timed_test => 'Timed Test';
	String get settings_timed_test_sub => 'Enable a time limit for the test';
	String get settings_instant_marking => 'Instant Marking';
	String get settings_instant_marking_sub => 'Show correct answer after each question';
	String get settings_num_questions => 'Number of Questions';
	String get settings_enter_num => 'Enter number of questions:';
	String get settings_include_saved => 'Include Saved Questions';
	String get settings_include_saved_sub => 'Include questions you previously saved';
	String get settings_dark_mode => 'Dark Mode';
	String get settings_dark_mode_sub => 'Switch between light and dark theme';
	String get settings_language => 'Language';
	String get settings_language_sub => 'Choose your preferred language';
	String get settings_version => 'Version Information';
	String get settings_app_version => 'App Version';
	String get settings_commit => 'Commit';
	String get settings_branch => 'Branch';
	String get settings_last_update => 'Last Update';
	String get settings_date => 'Date';
	String get settings_saved => 'Settings saved successfully';
	String get profile_student => 'STUDENT';
	String get profile_edit => 'Edit profile';
	String get profile_stats => 'My stats';
	String get profile_settings => 'Settings';
	String get profile_invite => 'Invite a friend';
	String get profile_help => 'Help';
	String get profile_logout_confirm => 'Are you sure you want to log out?';
	String get profile_yes_logout => 'Yes, Logout';
	String get home_dashboard => 'Dashboard';
	String get home_my_progress => 'My Progress';
	String get home_overall_score => 'Overall Score';
	String get home_passed => 'Passed';
	String get home_failed => 'Failed';
	String get home_total => 'Total';
	String get home_in_progress => 'In Progress';
	String get home_recent_activity => 'Recent Activity';
	String get home_by_category => 'By Category';
	String get home_this_week => 'This Week';
	String get home_this_month => 'This Month';
	String get home_no_attempts => 'No attempts yet!';
	String get home_no_attempts_sub => 'Once you complete a quiz, your results will show up here.';
	String get home_take_quiz => 'Take Your First Quiz';
	String get home_paused => 'Paused';
	String get home_resume => 'Resume';
	String get home_attempts => 'attempts';
	String get home_active => 'active';
	String get home_tests => 'tests';
	String get intro_slide1_body => 'Learn and practice for your license with ease.';
	String get intro_slide2_title => 'Interactive Tests';
	String get intro_slide2_body => 'Practice tests with real-time feedback and explanations.';
	String get intro_slide3_title => 'Get Certified';
	String get intro_slide3_body => 'Ace your exams and become a certified driver.';
	String get intro_skip => 'Skip';
	String get intro_get_started => 'Get Started';
	String get auth_welcome_title => 'Welcome to Drive Test!';
	String get auth_welcome_subtitle => 'Practice. Pass with confidence.';
	String get auth_login_btn => 'LOGIN';
	String get auth_signup_btn => 'SIGNUP';
	String get auth_skip_demo => 'SKIP FOR NOW (TRY DEMO)';
	String get auth_demo_error => 'Failed to login with demo account. Please try again.';
	String get auth_or => 'OR';
	String get auth_login_title => 'Login';
	String get auth_contact_support => 'Contact support';
	String get auth_username => 'Username';
	String get auth_email => 'Email';
	String get auth_password => 'Password';
	String get auth_remember_me => 'Remember me';
	String get auth_forgot_password => 'Forgot Password?';
	String get auth_invalid_credentials => 'Invalid username or password';
	String get auth_no_account => 'Don\'t have an account? ';
	String get auth_sign_up_link => 'Sign up';
	String get auth_skip_demo_short => 'Skip for now (Try Demo)';
	String get auth_google_continue => 'Continue with Google';
	String get auth_feedback_type => 'Type';
	String get auth_feedback_email_optional => 'Email (optional)';
	String get auth_feedback_subject_optional => 'Subject (optional)';
	String get auth_feedback_message => 'Message';
	String get auth_feedback_sent => 'Thanks! Your feedback was sent.';
	String get auth_feedback_error => 'Could not send feedback. Please try again.';
	String get auth_submit => 'Submit';
	String get auth_feedback_login_issue => 'Login issue';
	String get auth_feedback_signup_issue => 'Signup issue';
	String get auth_feedback_app_issue => 'App issue';
	String get auth_feedback_feature_request => 'Feature request';
	String get auth_feedback_other => 'Other';
	String get auth_create_account => 'Create Account';
	String get auth_sign_up_btn => 'Sign Up';
	String get auth_val_username_required => 'Please enter a username';
	String get auth_val_username_length => 'Username must be at least 4 characters';
	String get auth_val_email_required => 'Please enter an email';
	String get auth_val_email_invalid => 'Please enter a valid email';
	String get auth_val_password_required => 'Please enter a password';
	String get auth_val_password_length => 'Password must be at least 6 characters';
	String get auth_signup_success => 'Signup successful! Please login.';
	String get auth_welcome_first_login => 'Welcome. Enjoy exam prep.';
	String get auth_welcome_returning => 'Welcome back again.';
	String get auth_deleted_account_welcome_back => 'Always welcome back.';
	String get auth_signup_failed => 'Signup failed. Please correct the errors.';
	String get auth_generic_error => 'An error occurred. Please try again.';
	String get auth_express_google => 'Express login via Google';
	String get auth_google_label => 'Google';
	String get auth_tab_login => 'Log in';
	String get auth_tab_signup => 'Sign up';
	String get auth_show_password => 'Show';
	String get auth_hide_password => 'Hide';
	String get auth_forgot_title => 'Forgot Password';
	String get auth_forgot_heading => 'Reset Your Password';
	String get auth_forgot_subtitle => 'Enter your email address and we\'ll send you instructions to reset your password.';
	String get auth_forgot_email_label => 'Email Address';
	String get auth_forgot_send_btn => 'Send Reset Instructions';
	String get auth_forgot_back_login => 'Back to Login';
	String get auth_forgot_success => 'Password reset instructions have been sent to your email.';
	String get auth_forgot_error => 'Failed to send reset email. Please try again.';
	String get purchase_success_title => 'Your Purchase has\nbeen confirmed';
	String get purchase_success_start_tests => 'Start Tests';
	String get purchase_success_back_home => 'Back to home';
	String get bcd_drive_test => 'Drive Test';
	String get bcd_exams => 'Exams';
	String get bcd_exams_sub => 'Licences, categories & tests';
	String get bcd_traffic_signs => 'Traffic Signs';
	String get bcd_traffic_signs_sub => 'Browse all traffic signs';
	String get bcd_subscriptions => 'Subscriptions';
	String get bcd_subscriptions_sub => 'View plans & manage access';
	String get bcd_hub_practice => 'Practice';
	String get bcd_hub_tests => 'Tests';
	String get bcd_hub_theory_docs => 'Theory\nDocuments';
	String get bcd_hub_traffic_signs => 'Traffic Signs';
	String get bcd_hub_checklist => 'Checklist';
	String get bcd_hub_statistics => 'Statistics';
	String get bcd_hub_saved_questions => 'Saved\nQuestions';
	String get bcd_no_free_practice => 'No free practice test available for this category.';
	String get bcd_failed_practice => 'Failed to load practice test.';
	String get bcd_no_saved_questions => 'No saved questions in this category yet.';
	String get bcd_no_saved_questions_found => 'No saved questions found in this category.';
	String get bcd_failed_saved => 'Failed to load saved questions.';
	String get bcd_no_subscription => 'You don\'t have an active subscription for this category';
	String get bcd_free_content_desc => 'Practice, Traffic Signs, Documents and Checklists are free. Subscribe to unlock Tests.';
	String get bcd_buy_subscription => 'Buy subscription';
	String get bcd_buy_subscription_arrow => 'Buy subscription →';
	String get bcd_not_subscribed => 'You\'re not subscribed to this category';
	String get bcd_only_free_tests => 'Only free practice tests are available. Subscribe to unlock all tests.';
	String get bcd_no_free_practice_tests => 'No free practice tests available.';
	String get bcd_no_tests => 'No tests available.';
	String get bcd_no_documents => 'No documents available.';
	String get bcd_no_checklists => 'No checklists available.';
	String get bcd_failed_tests => 'Failed to load tests';
	String get bcd_subscription_required => 'Subscription Required';
	String get bcd_subscribe_access => 'Subscribe to access "{name}" and all its content.';
	String get bcd_not_now => 'Not now';
	String get bcd_buy => 'Buy';
	String get bcd_payment_failed => 'Payment failed. Please try again.';
	String get bcd_feedback_unavailable => 'Feedback is unavailable for this question.';
	String get bcd_feedback_submitted => 'Thanks! Your feedback was submitted.';
	String get bcd_feedback_failed => 'Could not submit feedback. Please try again.';
	String get bcd_categories => 'Categories';
	String get bcd_search_categories => 'Search categories…';
	String get bcd_no_categories => 'No categories available.';
	String get bcd_no_match_search => 'No matches found.';
	String get bcd_subscribed => 'Subscribed';
	String get bcd_tap_to_subscribe => 'Tap to subscribe';
	String get bcd_failed_categories => 'Failed to load categories';
	String get bcd_plans_tab => 'Plans';
	String get bcd_my_subscriptions_tab => 'My Subscriptions';
	String get bcd_no_plans => 'No plans available';
	String get bcd_active_label => 'Active';
	String get bcd_subscribe_btn => 'Subscribe';
	String get bcd_no_active_subscriptions => 'No active subscriptions';
	String get bcd_browse_plans => 'Browse plans to get started';
	String get bcd_expires => 'Expires';
	String get bcd_failed_plans => 'Failed to load plans';
	String get bcd_no_categories_linked => 'No categories linked to this subscription';
	String get bcd_failed_category => 'Failed to load category';
	String get bcd_search_signs => 'Search sign groups…';
	String get bcd_no_signs => 'No signs found';
	String get bcd_no_image => 'No image';
	String get bcd_signs_count_label => 'traffic signs';
	String get bcd_view => 'View';
	String get bcd_previous => 'Previous';
	String get bcd_next => 'Next';
	String get bcd_failed_traffic_signs => 'Failed to load traffic signs';
	String get bcd_search_hint => 'Search…';
	String get bcd_no_subcategories => 'No sub-categories available.';
	String get bcd_failed_subcategories => 'Failed to load sub-categories';
	String get bcd_no_questions => 'No questions found for this test.';
	String get bcd_failed_test_questions => 'Failed to load test questions.';
	String get bcd_questions_label => 'questions';
	String get bcd_pass_label => 'Pass';
	String get bcd_free_label => 'FREE';
	String get settings_theme_label => 'Theme';
	String get settings_theme_sub => 'Light, dark or follow system';
	String get settings_theme_system => 'System';
	String get settings_theme_light => 'Light';
	String get settings_theme_dark => 'Dark';
	String get help_title => 'Help & Support';
	String get help_need_help => 'Need Help?';
	String get help_subtitle => 'Tell us about your issue and we\'ll get back to you soon.';
	String get help_your_information => 'Your Information';
	String get help_username => 'Username';
	String get help_email => 'Email';
	String get help_user_id => 'User ID';
	String get help_subject => 'Subject';
	String get help_subject_hint => 'e.g., Login issue, Bug report, Feature request';
	String get help_subject_required => 'Please enter a subject';
	String get help_description => 'Description';
	String get help_description_hint => 'Please describe your issue in detail...';
	String get help_description_required => 'Please describe your issue';
	String get help_description_too_short => 'Please provide more details (at least 10 characters)';
	String get help_submit => 'Submit Report';
	String get help_or_email => 'Or email us directly at mohsin.sapra@gmail.com';
	String get help_opening_email => 'Opening email app...';
	String get help_email_error => 'Could not open email app. Please email mohsin.sapra@gmail.com directly.';
	String get help_generic_error => 'Error opening email app. Please try again.';
	String get notifications_title => 'Notifications';
	String get notifications_mark_all_read => 'Mark all read';
	String get notifications_clear => 'Clear';
	String get notifications_clear_confirm_title => 'Clear all notifications?';
	String get notifications_clear_confirm_body => 'This will remove all notifications. This action cannot be undone.';
	String get notifications_empty_title => 'No notifications';
	String get notifications_empty_subtitle => 'You\'re all caught up! We\'ll let you know when something new arrives.';
	String get notifications_just_now => 'Just now';
	String get notifications_minutes_ago => '{n} min ago';
	String get notifications_hours_ago => '{n}h ago';
	String get notifications_days_ago => '{n}d ago';
	String get image_viewer_swipe_to_close => 'Swipe down to close';
	String get image_viewer_load_error => 'Could not load image';
	String get dash_my_progress => 'My Progress';
	String get dash_sync_from_server => 'Sync from server';
	String get dash_unknown_error => 'Unknown error';
	String get dash_retry => 'Retry';
	String get dash_my_exams => 'My Exams';
	String get dash_tap_to_dive => 'Tap an exam to dive in';
	String get dash_overview => 'Overview';
	String get dash_categories_header => 'Categories';
	String get dash_batches_header => 'Batches';
	String get dash_expand_categories => 'Expand each category to see batches';
	String get dash_weekly_streak => 'Weekly Streak';
	String get dash_consistency_builds => 'Consistency builds mastery';
	String get dash_smart_insights => 'Smart Insights';
	String get dash_based_on_attempts => 'Based on your attempts';
	String get dash_continue_label => 'Continue: {name}';
	String get dash_total_attempts => 'Total Attempts';
	String get dash_batches_done => 'Batches Done';
	String get dash_avg_time => 'Avg Time';
	String get dash_weakest_label => 'Weakest: {name} ({score}%)';
	String get dash_batches_completed_label => '{done}/{total} batches completed';
	String get dash_weakness_low_score => 'Low score';
	String get dash_weakness_over_time => 'Over time';
	String get dash_weakness_needs_work => 'Needs work';
	String get dash_weakness_on_track => 'On track';
	String get dash_not_started => 'Not started';
	String get dash_attempt_one => '1 attempt';
	String get dash_attempt_many => '{n} attempts';
	String get dash_avg_duration => 'Avg {duration}';
	String get dash_over_time_pct => '+{pct}% time';
	String get dash_on_time => 'On time';
	String get dash_insight_strongest => 'Strongest area';
	String get dash_insight_weakest => 'Weakest area';
	String get dash_insight_focus => 'Focus recommendation';
	String get dash_insight_continue_learning => 'Continue learning';
	String get dash_insight_area_detail => '{name} — {score}% avg';
	String get dash_insight_focus_detail => 'Work on {name} next to keep progressing';
	String get dash_insight_start => 'Start with {name} — pick any batch to begin.';
	String get dash_insight_all_done => 'All batches completed! Revisit low-scoring batches to master them.';
	String get dash_insight_progress => '{done}/{total} batches passed. Keep going — you\'re {pct}% there!';
	String get dash_streak_current => 'Current\nStreak';
	String get dash_streak_best => 'Best\nStreak';
	String get dash_streak_weekly_goal => 'Weekly goal';
	String get dash_day_mon => 'M';
	String get dash_day_tue => 'T';
	String get dash_day_wed => 'W';
	String get dash_day_thu => 'T';
	String get dash_day_fri => 'F';
	String get dash_day_sat => 'S';
	String get dash_day_sun => 'S';
	String get dash_streak_msg_none => 'Start a session today to begin your streak!';
	String get dash_streak_msg_amazing => 'Amazing! {n} days in a row — keep it up!';
	String get dash_streak_msg_goal => 'Weekly goal reached! You\'re on fire 🔥';
	String get dash_streak_msg_progress_one => '{n} day streak! 1 more session to hit your weekly goal.';
	String get dash_streak_msg_progress_other => '{n} day streak! {left} more sessions to hit your weekly goal.';
	String get dash_completed => 'Completed!';
	String get dash_tap_to_explore => 'Tap to explore';

	String get onb_which_exams => 'Which exams are you preparing for?';
	String get onb_select_all_apply => 'Select all that apply';
	String get onb_exam_date_title => 'When is your exam?';
	String get onb_exam_date_subtitle => 'Set a target date to stay on track';
	String get onb_practice_days_title => 'How many days a week will you practice?';
	String get onb_practice_days_subtitle => 'Be realistic — consistency is key';
	String get onb_recommendations_title => 'Recommended for you';
	String get onb_recommendations_subtitle => 'Subscribe to unlock full access to these exams';
	String get onb_continue => 'Continue';
	String get onb_get_started => 'Get Started';
	String get onb_1_week => '1 week';
	String get onb_2_weeks => '2 weeks';
	String get onb_3_weeks => '3 weeks';
	String get onb_1_month => '1 month';
	String get onb_2_months => '2 months';
	String get onb_3_months => '3 months';
	String get onb_custom_date => 'Custom date';
	String get onb_subscribe => 'Subscribe';
	String get onb_no_exams => 'No exams available right now';
	String onb_days_week_label({required Object n}) => '${n} days/week';
	String onb_step_of({required Object current, required Object total}) => 'Step ${current} of ${total}';

	String get dash_exam_deadline => 'Exam Deadline';
	String dash_days_remaining({required Object n}) => '${n} days left';
	String get dash_deadline_today => 'Today!';
	String get dash_deadline_passed => 'Deadline passed';
	String get dash_no_deadline => 'No deadline set';
	String get dash_set_deadline => 'Set deadline';
	String get dash_change_deadline => 'Change deadline';
	String dash_practice_days({required Object n}) => '${n} days/week';
}

/// Flat map(s) containing all translations.
/// Only for edge cases! For simple maps, use the map function of this library.
extension on Translations {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'home': return 'Home';
			case 'tests': return 'Tests';
			case 'profile': return 'Profile';
			case 'welcome_message': return 'Welcome to Drive Test';
			case 'save': return 'Save';
			case 'cancel': return 'Cancel';
			case 'delete': return 'Delete';
			case 'logout': return 'Logout';
			case 'loading': return 'Loading...';
			case 'settings_title': return 'Settings';
			case 'settings_appearance': return 'Appearance';
			case 'settings_test_prefs': return 'Test Preferences';
			case 'settings_timed_test': return 'Timed Test';
			case 'settings_timed_test_sub': return 'Enable a time limit for the test';
			case 'settings_instant_marking': return 'Instant Marking';
			case 'settings_instant_marking_sub': return 'Show correct answer after each question';
			case 'settings_num_questions': return 'Number of Questions';
			case 'settings_enter_num': return 'Enter number of questions:';
			case 'settings_include_saved': return 'Include Saved Questions';
			case 'settings_include_saved_sub': return 'Include questions you previously saved';
			case 'settings_dark_mode': return 'Dark Mode';
			case 'settings_dark_mode_sub': return 'Switch between light and dark theme';
			case 'settings_language': return 'Language';
			case 'settings_language_sub': return 'Choose your preferred language';
			case 'settings_version': return 'Version Information';
			case 'settings_app_version': return 'App Version';
			case 'settings_commit': return 'Commit';
			case 'settings_branch': return 'Branch';
			case 'settings_last_update': return 'Last Update';
			case 'settings_date': return 'Date';
			case 'settings_saved': return 'Settings saved successfully';
			case 'profile_student': return 'STUDENT';
			case 'profile_edit': return 'Edit profile';
			case 'profile_stats': return 'My stats';
			case 'profile_settings': return 'Settings';
			case 'profile_invite': return 'Invite a friend';
			case 'profile_help': return 'Help';
			case 'profile_logout_confirm': return 'Are you sure you want to log out?';
			case 'profile_yes_logout': return 'Yes, Logout';
			case 'home_dashboard': return 'Dashboard';
			case 'home_my_progress': return 'My Progress';
			case 'home_overall_score': return 'Overall Score';
			case 'home_passed': return 'Passed';
			case 'home_failed': return 'Failed';
			case 'home_total': return 'Total';
			case 'home_in_progress': return 'In Progress';
			case 'home_recent_activity': return 'Recent Activity';
			case 'home_by_category': return 'By Category';
			case 'home_this_week': return 'This Week';
			case 'home_this_month': return 'This Month';
			case 'home_no_attempts': return 'No attempts yet!';
			case 'home_no_attempts_sub': return 'Once you complete a quiz, your results will show up here.';
			case 'home_take_quiz': return 'Take Your First Quiz';
			case 'home_paused': return 'Paused';
			case 'home_resume': return 'Resume';
			case 'home_attempts': return 'attempts';
			case 'home_active': return 'active';
			case 'home_tests': return 'tests';
			case 'intro_slide1_body': return 'Learn and practice for your license with ease.';
			case 'intro_slide2_title': return 'Interactive Tests';
			case 'intro_slide2_body': return 'Practice tests with real-time feedback and explanations.';
			case 'intro_slide3_title': return 'Get Certified';
			case 'intro_slide3_body': return 'Ace your exams and become a certified driver.';
			case 'intro_skip': return 'Skip';
			case 'intro_get_started': return 'Get Started';
			case 'auth_welcome_title': return 'Welcome to Drive Test!';
			case 'auth_welcome_subtitle': return 'Practice. Pass with confidence.';
			case 'auth_login_btn': return 'LOGIN';
			case 'auth_signup_btn': return 'SIGNUP';
			case 'auth_skip_demo': return 'SKIP FOR NOW (TRY DEMO)';
			case 'auth_demo_error': return 'Failed to login with demo account. Please try again.';
			case 'auth_or': return 'OR';
			case 'auth_login_title': return 'Login';
			case 'auth_contact_support': return 'Contact support';
			case 'auth_username': return 'Username';
			case 'auth_email': return 'Email';
			case 'auth_password': return 'Password';
			case 'auth_remember_me': return 'Remember me';
			case 'auth_forgot_password': return 'Forgot Password?';
			case 'auth_invalid_credentials': return 'Invalid username or password';
			case 'auth_no_account': return 'Don\'t have an account? ';
			case 'auth_sign_up_link': return 'Sign up';
			case 'auth_skip_demo_short': return 'Skip for now (Try Demo)';
			case 'auth_google_continue': return 'Continue with Google';
			case 'auth_feedback_type': return 'Type';
			case 'auth_feedback_email_optional': return 'Email (optional)';
			case 'auth_feedback_subject_optional': return 'Subject (optional)';
			case 'auth_feedback_message': return 'Message';
			case 'auth_feedback_sent': return 'Thanks! Your feedback was sent.';
			case 'auth_feedback_error': return 'Could not send feedback. Please try again.';
			case 'auth_submit': return 'Submit';
			case 'auth_feedback_login_issue': return 'Login issue';
			case 'auth_feedback_signup_issue': return 'Signup issue';
			case 'auth_feedback_app_issue': return 'App issue';
			case 'auth_feedback_feature_request': return 'Feature request';
			case 'auth_feedback_other': return 'Other';
			case 'auth_create_account': return 'Create Account';
			case 'auth_sign_up_btn': return 'Sign Up';
			case 'auth_val_username_required': return 'Please enter a username';
			case 'auth_val_username_length': return 'Username must be at least 4 characters';
			case 'auth_val_email_required': return 'Please enter an email';
			case 'auth_val_email_invalid': return 'Please enter a valid email';
			case 'auth_val_password_required': return 'Please enter a password';
			case 'auth_val_password_length': return 'Password must be at least 6 characters';
			case 'auth_signup_success': return 'Signup successful! Please login.';
			case 'auth_welcome_first_login': return 'Welcome. Enjoy exam prep.';
			case 'auth_welcome_returning': return 'Welcome back again.';
			case 'auth_deleted_account_welcome_back': return 'Always welcome back.';
			case 'auth_signup_failed': return 'Signup failed. Please correct the errors.';
			case 'auth_generic_error': return 'An error occurred. Please try again.';
			case 'auth_express_google': return 'Express login via Google';
			case 'auth_google_label': return 'Google';
			case 'auth_tab_login': return 'Log in';
			case 'auth_tab_signup': return 'Sign up';
			case 'auth_show_password': return 'Show';
			case 'auth_hide_password': return 'Hide';
			case 'auth_forgot_title': return 'Forgot Password';
			case 'auth_forgot_heading': return 'Reset Your Password';
			case 'auth_forgot_subtitle': return 'Enter your email address and we\'ll send you instructions to reset your password.';
			case 'auth_forgot_email_label': return 'Email Address';
			case 'auth_forgot_send_btn': return 'Send Reset Instructions';
			case 'auth_forgot_back_login': return 'Back to Login';
			case 'auth_forgot_success': return 'Password reset instructions have been sent to your email.';
			case 'auth_forgot_error': return 'Failed to send reset email. Please try again.';
			case 'purchase_success_title': return 'Your Purchase has\nbeen confirmed';
			case 'purchase_success_start_tests': return 'Start Tests';
			case 'purchase_success_back_home': return 'Back to home';
			case 'bcd_drive_test': return 'Drive Test';
			case 'bcd_exams': return 'Exams';
			case 'bcd_exams_sub': return 'Licences, categories & tests';
			case 'bcd_traffic_signs': return 'Traffic Signs';
			case 'bcd_traffic_signs_sub': return 'Browse all traffic signs';
			case 'bcd_subscriptions': return 'Subscriptions';
			case 'bcd_subscriptions_sub': return 'View plans & manage access';
			case 'bcd_hub_practice': return 'Practice';
			case 'bcd_hub_tests': return 'Tests';
			case 'bcd_hub_theory_docs': return 'Theory\nDocuments';
			case 'bcd_hub_traffic_signs': return 'Traffic Signs';
			case 'bcd_hub_checklist': return 'Checklist';
			case 'bcd_hub_statistics': return 'Statistics';
			case 'bcd_hub_saved_questions': return 'Saved\nQuestions';
			case 'bcd_no_free_practice': return 'No free practice test available for this category.';
			case 'bcd_failed_practice': return 'Failed to load practice test.';
			case 'bcd_no_saved_questions': return 'No saved questions in this category yet.';
			case 'bcd_no_saved_questions_found': return 'No saved questions found in this category.';
			case 'bcd_failed_saved': return 'Failed to load saved questions.';
			case 'bcd_no_subscription': return 'You don\'t have an active subscription for this category';
			case 'bcd_free_content_desc': return 'Practice, Traffic Signs, Documents and Checklists are free. Subscribe to unlock Tests.';
			case 'bcd_buy_subscription': return 'Buy subscription';
			case 'bcd_buy_subscription_arrow': return 'Buy subscription →';
			case 'bcd_not_subscribed': return 'You\'re not subscribed to this category';
			case 'bcd_only_free_tests': return 'Only free practice tests are available. Subscribe to unlock all tests.';
			case 'bcd_no_free_practice_tests': return 'No free practice tests available.';
			case 'bcd_no_tests': return 'No tests available.';
			case 'bcd_no_documents': return 'No documents available.';
			case 'bcd_no_checklists': return 'No checklists available.';
			case 'bcd_failed_tests': return 'Failed to load tests';
			case 'bcd_subscription_required': return 'Subscription Required';
			case 'bcd_subscribe_access': return 'Subscribe to access "{name}" and all its content.';
			case 'bcd_not_now': return 'Not now';
			case 'bcd_buy': return 'Buy';
			case 'bcd_payment_failed': return 'Payment failed. Please try again.';
			case 'bcd_feedback_unavailable': return 'Feedback is unavailable for this question.';
			case 'bcd_feedback_submitted': return 'Thanks! Your feedback was submitted.';
			case 'bcd_feedback_failed': return 'Could not submit feedback. Please try again.';
			case 'bcd_categories': return 'Categories';
			case 'bcd_search_categories': return 'Search categories…';
			case 'bcd_no_categories': return 'No categories available.';
			case 'bcd_no_match_search': return 'No matches found.';
			case 'bcd_subscribed': return 'Subscribed';
			case 'bcd_tap_to_subscribe': return 'Tap to subscribe';
			case 'bcd_failed_categories': return 'Failed to load categories';
			case 'bcd_plans_tab': return 'Plans';
			case 'bcd_my_subscriptions_tab': return 'My Subscriptions';
			case 'bcd_no_plans': return 'No plans available';
			case 'bcd_active_label': return 'Active';
			case 'bcd_subscribe_btn': return 'Subscribe';
			case 'bcd_no_active_subscriptions': return 'No active subscriptions';
			case 'bcd_browse_plans': return 'Browse plans to get started';
			case 'bcd_expires': return 'Expires';
			case 'bcd_failed_plans': return 'Failed to load plans';
			case 'bcd_no_categories_linked': return 'No categories linked to this subscription';
			case 'bcd_failed_category': return 'Failed to load category';
			case 'bcd_search_signs': return 'Search sign groups…';
			case 'bcd_no_signs': return 'No signs found';
			case 'bcd_no_image': return 'No image';
			case 'bcd_signs_count_label': return 'traffic signs';
			case 'bcd_view': return 'View';
			case 'bcd_previous': return 'Previous';
			case 'bcd_next': return 'Next';
			case 'bcd_failed_traffic_signs': return 'Failed to load traffic signs';
			case 'bcd_search_hint': return 'Search…';
			case 'bcd_no_subcategories': return 'No sub-categories available.';
			case 'bcd_failed_subcategories': return 'Failed to load sub-categories';
			case 'bcd_no_questions': return 'No questions found for this test.';
			case 'bcd_failed_test_questions': return 'Failed to load test questions.';
			case 'bcd_questions_label': return 'questions';
			case 'bcd_pass_label': return 'Pass';
			case 'bcd_free_label': return 'FREE';
			case 'settings_theme_label': return 'Theme';
			case 'settings_theme_sub': return 'Light, dark or follow system';
			case 'settings_theme_system': return 'System';
			case 'settings_theme_light': return 'Light';
			case 'settings_theme_dark': return 'Dark';
			case 'help_title': return 'Help & Support';
			case 'help_need_help': return 'Need Help?';
			case 'help_subtitle': return 'Tell us about your issue and we\'ll get back to you soon.';
			case 'help_your_information': return 'Your Information';
			case 'help_username': return 'Username';
			case 'help_email': return 'Email';
			case 'help_user_id': return 'User ID';
			case 'help_subject': return 'Subject';
			case 'help_subject_hint': return 'e.g., Login issue, Bug report, Feature request';
			case 'help_subject_required': return 'Please enter a subject';
			case 'help_description': return 'Description';
			case 'help_description_hint': return 'Please describe your issue in detail...';
			case 'help_description_required': return 'Please describe your issue';
			case 'help_description_too_short': return 'Please provide more details (at least 10 characters)';
			case 'help_submit': return 'Submit Report';
			case 'help_or_email': return 'Or email us directly at mohsin.sapra@gmail.com';
			case 'help_opening_email': return 'Opening email app...';
			case 'help_email_error': return 'Could not open email app. Please email mohsin.sapra@gmail.com directly.';
			case 'help_generic_error': return 'Error opening email app. Please try again.';
			case 'notifications_title': return 'Notifications';
			case 'notifications_mark_all_read': return 'Mark all read';
			case 'notifications_clear': return 'Clear';
			case 'notifications_clear_confirm_title': return 'Clear all notifications?';
			case 'notifications_clear_confirm_body': return 'This will remove all notifications. This action cannot be undone.';
			case 'notifications_empty_title': return 'No notifications';
			case 'notifications_empty_subtitle': return 'You\'re all caught up! We\'ll let you know when something new arrives.';
			case 'notifications_just_now': return 'Just now';
			case 'notifications_minutes_ago': return '{n} min ago';
			case 'notifications_hours_ago': return '{n}h ago';
			case 'notifications_days_ago': return '{n}d ago';
			case 'image_viewer_swipe_to_close': return 'Swipe down to close';
			case 'image_viewer_load_error': return 'Could not load image';
			case 'dash_my_progress': return 'My Progress';
			case 'dash_sync_from_server': return 'Sync from server';
			case 'dash_unknown_error': return 'Unknown error';
			case 'dash_retry': return 'Retry';
			case 'dash_my_exams': return 'My Exams';
			case 'dash_tap_to_dive': return 'Tap an exam to dive in';
			case 'dash_overview': return 'Overview';
			case 'dash_categories_header': return 'Categories';
			case 'dash_batches_header': return 'Batches';
			case 'dash_expand_categories': return 'Expand each category to see batches';
			case 'dash_weekly_streak': return 'Weekly Streak';
			case 'dash_consistency_builds': return 'Consistency builds mastery';
			case 'dash_smart_insights': return 'Smart Insights';
			case 'dash_based_on_attempts': return 'Based on your attempts';
			case 'dash_continue_label': return 'Continue: {name}';
			case 'dash_total_attempts': return 'Total Attempts';
			case 'dash_batches_done': return 'Batches Done';
			case 'dash_avg_time': return 'Avg Time';
			case 'dash_weakest_label': return 'Weakest: {name} ({score}%)';
			case 'dash_batches_completed_label': return '{done}/{total} batches completed';
			case 'dash_weakness_low_score': return 'Low score';
			case 'dash_weakness_over_time': return 'Over time';
			case 'dash_weakness_needs_work': return 'Needs work';
			case 'dash_weakness_on_track': return 'On track';
			case 'dash_not_started': return 'Not started';
			case 'dash_attempt_one': return '1 attempt';
			case 'dash_attempt_many': return '{n} attempts';
			case 'dash_avg_duration': return 'Avg {duration}';
			case 'dash_over_time_pct': return '+{pct}% time';
			case 'dash_on_time': return 'On time';
			case 'dash_insight_strongest': return 'Strongest area';
			case 'dash_insight_weakest': return 'Weakest area';
			case 'dash_insight_focus': return 'Focus recommendation';
			case 'dash_insight_continue_learning': return 'Continue learning';
			case 'dash_insight_area_detail': return '{name} — {score}% avg';
			case 'dash_insight_focus_detail': return 'Work on {name} next to keep progressing';
			case 'dash_insight_start': return 'Start with {name} — pick any batch to begin.';
			case 'dash_insight_all_done': return 'All batches completed! Revisit low-scoring batches to master them.';
			case 'dash_insight_progress': return '{done}/{total} batches passed. Keep going — you\'re {pct}% there!';
			case 'dash_streak_current': return 'Current\nStreak';
			case 'dash_streak_best': return 'Best\nStreak';
			case 'dash_streak_weekly_goal': return 'Weekly goal';
			case 'dash_day_mon': return 'M';
			case 'dash_day_tue': return 'T';
			case 'dash_day_wed': return 'W';
			case 'dash_day_thu': return 'T';
			case 'dash_day_fri': return 'F';
			case 'dash_day_sat': return 'S';
			case 'dash_day_sun': return 'S';
			case 'dash_streak_msg_none': return 'Start a session today to begin your streak!';
			case 'dash_streak_msg_amazing': return 'Amazing! {n} days in a row — keep it up!';
			case 'dash_streak_msg_goal': return 'Weekly goal reached! You\'re on fire 🔥';
			case 'dash_streak_msg_progress_one': return '{n} day streak! 1 more session to hit your weekly goal.';
			case 'dash_streak_msg_progress_other': return '{n} day streak! {left} more sessions to hit your weekly goal.';
			case 'dash_completed': return 'Completed!';
			case 'dash_tap_to_explore': return 'Tap to explore';
			case 'onb_which_exams': return 'Which exams are you preparing for?';
			case 'onb_select_all_apply': return 'Select all that apply';
			case 'onb_exam_date_title': return 'When is your exam?';
			case 'onb_exam_date_subtitle': return 'Set a target date to stay on track';
			case 'onb_practice_days_title': return 'How many days a week will you practice?';
			case 'onb_practice_days_subtitle': return 'Be realistic — consistency is key';
			case 'onb_recommendations_title': return 'Recommended for you';
			case 'onb_recommendations_subtitle': return 'Subscribe to unlock full access to these exams';
			case 'onb_continue': return 'Continue';
			case 'onb_get_started': return 'Get Started';
			case 'onb_1_week': return '1 week';
			case 'onb_2_weeks': return '2 weeks';
			case 'onb_3_weeks': return '3 weeks';
			case 'onb_1_month': return '1 month';
			case 'onb_2_months': return '2 months';
			case 'onb_3_months': return '3 months';
			case 'onb_custom_date': return 'Custom date';
			case 'onb_subscribe': return 'Subscribe';
			case 'onb_no_exams': return 'No exams available right now';
			case 'onb_days_week_label': return ({required Object n}) => '${n} days/week';
			case 'onb_step_of': return ({required Object current, required Object total}) => 'Step ${current} of ${total}';
			case 'dash_exam_deadline': return 'Exam Deadline';
			case 'dash_days_remaining': return ({required Object n}) => '${n} days left';
			case 'dash_deadline_today': return 'Today!';
			case 'dash_deadline_passed': return 'Deadline passed';
			case 'dash_no_deadline': return 'No deadline set';
			case 'dash_set_deadline': return 'Set deadline';
			case 'dash_change_deadline': return 'Change deadline';
			case 'dash_practice_days': return ({required Object n}) => '${n} days/week';
			default: return null;
		}
	}
}

