///
/// Generated file. Do not edit.
///
// coverage:ignore-file
// ignore_for_file: type=lint, unused_import

import 'package:flutter/widgets.dart';
import 'package:intl/intl.dart';
import 'package:slang/generated.dart';
import 'strings.g.dart';

// Path: <root>
class TranslationsSv implements Translations {
	/// You can call this constructor and build your own translation instance of this locale.
	/// Constructing via the enum [AppLocale.build] is preferred.
	TranslationsSv({Map<String, Node>? overrides, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver, TranslationMetadata<AppLocale, Translations>? meta})
		: assert(overrides == null, 'Set "translation_overrides: true" in order to enable this feature.'),
		  $meta = meta ?? TranslationMetadata(
		    locale: AppLocale.sv,
		    overrides: overrides ?? {},
		    cardinalResolver: cardinalResolver,
		    ordinalResolver: ordinalResolver,
		  ) {
		$meta.setFlatMapFunction(_flatMapFunction);
	}

	/// Metadata for the translations of <sv>.
	@override final TranslationMetadata<AppLocale, Translations> $meta;

	/// Access flat map
	@override dynamic operator[](String key) => $meta.getTranslation(key);

	late final TranslationsSv _root = this; // ignore: unused_field

	@override 
	TranslationsSv $copyWith({TranslationMetadata<AppLocale, Translations>? meta}) => TranslationsSv(meta: meta ?? this.$meta);

	// Translations
	@override String get home => 'Hem';
	@override String get tests => 'Prov';
	@override String get profile => 'Profil';
	@override String get welcome_message => 'Välkommen till Drive Test';
	@override String get save => 'Spara';
	@override String get cancel => 'Avbryt';
	@override String get delete => 'Ta bort';
	@override String get logout => 'Logga ut';
	@override String get loading => 'Laddar...';
	@override String get settings_title => 'Inställningar';
	@override String get settings_appearance => 'Utseende';
	@override String get settings_test_prefs => 'Provpreferenser';
	@override String get settings_timed_test => 'Tidsbegränsat prov';
	@override String get settings_timed_test_sub => 'Aktivera tidsgräns för provet';
	@override String get settings_instant_marking => 'Omedelbar rättning';
	@override String get settings_instant_marking_sub => 'Visa rätt svar efter varje fråga';
	@override String get settings_num_questions => 'Antal frågor';
	@override String get settings_enter_num => 'Ange antal frågor:';
	@override String get settings_include_saved => 'Inkludera sparade frågor';
	@override String get settings_include_saved_sub => 'Inkludera frågor du tidigare sparat';
	@override String get settings_dark_mode => 'Mörkt läge';
	@override String get settings_dark_mode_sub => 'Växla mellan ljust och mörkt tema';
	@override String get settings_language => 'Språk';
	@override String get settings_language_sub => 'Välj ditt föredragna språk';
	@override String get settings_version => 'Versionsinformation';
	@override String get settings_app_version => 'Appversion';
	@override String get settings_commit => 'Commit';
	@override String get settings_branch => 'Gren';
	@override String get settings_last_update => 'Senaste uppdatering';
	@override String get settings_date => 'Datum';
	@override String get settings_saved => 'Inställningar sparades';
	@override String get profile_student => 'STUDENT';
	@override String get profile_edit => 'Redigera profil';
	@override String get profile_stats => 'Mina resultat';
	@override String get profile_settings => 'Inställningar';
	@override String get profile_invite => 'Bjud in en vän';
	@override String get profile_help => 'Hjälp';
	@override String get profile_logout_confirm => 'Är du säker på att du vill logga ut?';
	@override String get profile_yes_logout => 'Ja, logga ut';
	@override String get home_dashboard => 'Instrumentpanel';
	@override String get home_my_progress => 'Min framsteg';
	@override String get home_overall_score => 'Totalt resultat';
	@override String get home_passed => 'Godkänd';
	@override String get home_failed => 'Underkänd';
	@override String get home_total => 'Totalt';
	@override String get home_in_progress => 'Pågående';
	@override String get home_recent_activity => 'Senaste aktivitet';
	@override String get home_by_category => 'Per kategori';
	@override String get home_this_week => 'Denna vecka';
	@override String get home_this_month => 'Denna månad';
	@override String get home_no_attempts => 'Inga försök än!';
	@override String get home_no_attempts_sub => 'När du slutfört ett prov visas dina resultat här.';
	@override String get home_take_quiz => 'Ta ditt första prov';
	@override String get home_paused => 'Pausad';
	@override String get home_resume => 'Återuppta';
	@override String get home_attempts => 'försök';
	@override String get home_active => 'aktiv';
	@override String get home_tests => 'prov';
	@override String get intro_slide1_body => 'Lär dig och öva inför ditt körkort enkelt.';
	@override String get intro_slide2_title => 'Interaktiva prov';
	@override String get intro_slide2_body => 'Övningsprov med direkt feedback och förklaringar.';
	@override String get intro_slide3_title => 'Bli godkänd';
	@override String get intro_slide3_body => 'Klara dina prov och bli en godkänd förare.';
	@override String get intro_skip => 'Hoppa över';
	@override String get intro_get_started => 'Kom igång';
	@override String get auth_welcome_title => 'Välkommen till Drive Test!';
	@override String get auth_welcome_subtitle => 'Öva. Klara prov tryggt.';
	@override String get auth_login_btn => 'LOGGA IN';
	@override String get auth_signup_btn => 'REGISTRERA';
	@override String get auth_skip_demo => 'HOPPA ÖVER (PROVA DEMO)';
	@override String get auth_demo_error => 'Kunde inte logga in med demokontot. Försök igen.';
	@override String get auth_or => 'ELLER';
	@override String get auth_login_title => 'Logga in';
	@override String get auth_contact_support => 'Kontakta support';
	@override String get auth_username => 'Användarnamn';
	@override String get auth_email => 'E-post';
	@override String get auth_password => 'Lösenord';
	@override String get auth_remember_me => 'Kom ihåg mig';
	@override String get auth_forgot_password => 'Glömt lösenord?';
	@override String get auth_invalid_credentials => 'Ogiltigt användarnamn eller lösenord';
	@override String get auth_no_account => 'Har du inget konto? ';
	@override String get auth_sign_up_link => 'Registrera dig';
	@override String get auth_skip_demo_short => 'Hoppa över (Prova demo)';
	@override String get auth_google_continue => 'Fortsätt med Google';
	@override String get auth_feedback_type => 'Typ';
	@override String get auth_feedback_email_optional => 'E-post (valfritt)';
	@override String get auth_feedback_subject_optional => 'Ämne (valfritt)';
	@override String get auth_feedback_message => 'Meddelande';
	@override String get auth_feedback_sent => 'Tack! Din feedback skickades.';
	@override String get auth_feedback_error => 'Kunde inte skicka feedback. Försök igen.';
	@override String get auth_submit => 'Skicka';
	@override String get auth_feedback_login_issue => 'Inloggningsproblem';
	@override String get auth_feedback_signup_issue => 'Registreringsproblem';
	@override String get auth_feedback_app_issue => 'Appproblem';
	@override String get auth_feedback_feature_request => 'Funktionsförfrågan';
	@override String get auth_feedback_other => 'Övrigt';
	@override String get auth_create_account => 'Skapa konto';
	@override String get auth_sign_up_btn => 'Registrera';
	@override String get auth_val_username_required => 'Vänligen ange ett användarnamn';
	@override String get auth_val_username_length => 'Användarnamnet måste vara minst 4 tecken';
	@override String get auth_val_email_required => 'Vänligen ange en e-postadress';
	@override String get auth_val_email_invalid => 'Vänligen ange en giltig e-postadress';
	@override String get auth_val_password_required => 'Vänligen ange ett lösenord';
	@override String get auth_val_password_length => 'Lösenordet måste vara minst 6 tecken';
	@override String get auth_signup_success => 'Registreringen lyckades! Vänligen logga in.';
	@override String get auth_welcome_first_login => 'Välkommen, lycka till!';
	@override String get auth_welcome_returning => 'Välkommen tillbaka igen!';
	@override String get auth_deleted_account_welcome_back => 'Alltid välkommen tillbaka.';
	@override String get auth_signup_failed => 'Registreringen misslyckades. Rätta felen.';
	@override String get auth_generic_error => 'Ett fel uppstod. Försök igen.';
	@override String get auth_express_google => 'Express-inloggning via Google';
	@override String get auth_google_label => 'Google';
	@override String get auth_tab_login => 'Logga in';
	@override String get auth_tab_signup => 'Registrera dig';
	@override String get auth_show_password => 'Visa';
	@override String get auth_hide_password => 'Dölj';
	@override String get auth_forgot_title => 'Glömt lösenord';
	@override String get auth_forgot_heading => 'Återställ ditt lösenord';
	@override String get auth_forgot_subtitle => 'Ange din e-postadress så skickar vi instruktioner för att återställa ditt lösenord.';
	@override String get auth_forgot_email_label => 'E-postadress';
	@override String get auth_forgot_send_btn => 'Skicka instruktioner';
	@override String get auth_forgot_back_login => 'Tillbaka till inloggning';
	@override String get auth_forgot_success => 'Instruktioner för lösenordsåterställning har skickats till din e-post.';
	@override String get auth_forgot_error => 'Det gick inte att skicka återställningsmail. Försök igen.';
	@override String get purchase_success_title => 'Ditt köp har\nbekräftats';
	@override String get purchase_success_start_tests => 'Starta prov';
	@override String get purchase_success_back_home => 'Tillbaka till start';
	@override String get bcd_drive_test => 'Drive Test';
	@override String get bcd_exams => 'Prov';
	@override String get bcd_exams_sub => 'Licenser, kategorier & prov';
	@override String get bcd_traffic_signs => 'Trafikskyltar';
	@override String get bcd_traffic_signs_sub => 'Bläddra bland alla trafikskyltar';
	@override String get bcd_subscriptions => 'Prenumerationer';
	@override String get bcd_subscriptions_sub => 'Visa planer och hantera åtkomst';
	@override String get bcd_hub_practice => 'Övning';
	@override String get bcd_hub_tests => 'Prov';
	@override String get bcd_hub_theory_docs => 'Teori-\ndokument';
	@override String get bcd_hub_traffic_signs => 'Trafikskyltar';
	@override String get bcd_hub_checklist => 'Checklista';
	@override String get bcd_hub_statistics => 'Statistik';
	@override String get bcd_hub_saved_questions => 'Sparade\nfrågor';
	@override String get bcd_no_free_practice => 'Inget gratis övningsprov tillgängligt för denna kategori.';
	@override String get bcd_failed_practice => 'Det gick inte att ladda övningsprovet.';
	@override String get bcd_no_saved_questions => 'Inga sparade frågor i denna kategori ännu.';
	@override String get bcd_no_saved_questions_found => 'Inga sparade frågor hittades i denna kategori.';
	@override String get bcd_failed_saved => 'Det gick inte att ladda sparade frågor.';
	@override String get bcd_no_subscription => 'Du har ingen aktiv prenumeration för denna kategori';
	@override String get bcd_free_content_desc => 'Övning, Trafikskyltar, Dokument och Checklistor är gratis. Prenumerera för att låsa upp Prov.';
	@override String get bcd_buy_subscription => 'Köp prenumeration';
	@override String get bcd_buy_subscription_arrow => 'Köp prenumeration →';
	@override String get bcd_not_subscribed => 'Du prenumererar inte på denna kategori';
	@override String get bcd_only_free_tests => 'Endast gratis övningsprov är tillgängliga. Prenumerera för att låsa upp alla prov.';
	@override String get bcd_no_free_practice_tests => 'Inga gratis övningsprov tillgängliga.';
	@override String get bcd_no_tests => 'Inga prov tillgängliga.';
	@override String get bcd_no_documents => 'Inga dokument tillgängliga.';
	@override String get bcd_no_checklists => 'Inga checklistor tillgängliga.';
	@override String get bcd_failed_tests => 'Det gick inte att ladda prov';
	@override String get bcd_subscription_required => 'Prenumeration krävs';
	@override String get bcd_subscribe_access => 'Prenumerera för att få tillgång till "{name}" och allt dess innehåll.';
	@override String get bcd_not_now => 'Inte nu';
	@override String get bcd_buy => 'Köp';
	@override String get bcd_payment_failed => 'Betalning misslyckades. Försök igen.';
	@override String get bcd_feedback_unavailable => 'Feedback ej tillgänglig för denna fråga.';
	@override String get bcd_feedback_submitted => 'Tack! Din feedback skickades.';
	@override String get bcd_feedback_failed => 'Kunde inte skicka feedback. Försök igen.';
	@override String get bcd_categories => 'Kategorier';
	@override String get bcd_search_categories => 'Sök kategorier…';
	@override String get bcd_no_categories => 'Inga kategorier tillgängliga.';
	@override String get bcd_no_match_search => 'Inga träffar hittades.';
	@override String get bcd_subscribed => 'Prenumererar';
	@override String get bcd_tap_to_subscribe => 'Tryck för att prenumerera';
	@override String get bcd_failed_categories => 'Det gick inte att ladda kategorier';
	@override String get bcd_plans_tab => 'Planer';
	@override String get bcd_my_subscriptions_tab => 'Mina prenumerationer';
	@override String get bcd_no_plans => 'Inga planer tillgängliga';
	@override String get bcd_active_label => 'Aktiv';
	@override String get bcd_subscribe_btn => 'Prenumerera';
	@override String get bcd_no_active_subscriptions => 'Inga aktiva prenumerationer';
	@override String get bcd_browse_plans => 'Bläddra bland planer för att komma igång';
	@override String get bcd_expires => 'Upphör';
	@override String get bcd_failed_plans => 'Det gick inte att ladda planer';
	@override String get bcd_no_categories_linked => 'Inga kategorier kopplade till den här prenumerationen';
	@override String get bcd_failed_category => 'Det gick inte att ladda kategorin';
	@override String get bcd_search_signs => 'Sök skyltgrupper…';
	@override String get bcd_no_signs => 'Inga skyltar hittades';
	@override String get bcd_no_image => 'Ingen bild';
	@override String get bcd_signs_count_label => 'trafikskyltar';
	@override String get bcd_view => 'Visa';
	@override String get bcd_previous => 'Föregående';
	@override String get bcd_next => 'Nästa';
	@override String get bcd_failed_traffic_signs => 'Det gick inte att ladda trafikskyltar';
	@override String get bcd_search_hint => 'Sök…';
	@override String get bcd_no_subcategories => 'Inga underkategorier tillgängliga.';
	@override String get bcd_failed_subcategories => 'Det gick inte att ladda underkategorier';
	@override String get bcd_no_questions => 'Inga frågor hittades för det här provet.';
	@override String get bcd_failed_test_questions => 'Det gick inte att ladda provfrågor.';
	@override String get bcd_questions_label => 'frågor';
	@override String get bcd_pass_label => 'Godkänt';
	@override String get bcd_free_label => 'GRATIS';
}

/// Flat map(s) containing all translations.
/// Only for edge cases! For simple maps, use the map function of this library.
extension on TranslationsSv {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'home': return 'Hem';
			case 'tests': return 'Prov';
			case 'profile': return 'Profil';
			case 'welcome_message': return 'Välkommen till Drive Test';
			case 'save': return 'Spara';
			case 'cancel': return 'Avbryt';
			case 'delete': return 'Ta bort';
			case 'logout': return 'Logga ut';
			case 'loading': return 'Laddar...';
			case 'settings_title': return 'Inställningar';
			case 'settings_appearance': return 'Utseende';
			case 'settings_test_prefs': return 'Provpreferenser';
			case 'settings_timed_test': return 'Tidsbegränsat prov';
			case 'settings_timed_test_sub': return 'Aktivera tidsgräns för provet';
			case 'settings_instant_marking': return 'Omedelbar rättning';
			case 'settings_instant_marking_sub': return 'Visa rätt svar efter varje fråga';
			case 'settings_num_questions': return 'Antal frågor';
			case 'settings_enter_num': return 'Ange antal frågor:';
			case 'settings_include_saved': return 'Inkludera sparade frågor';
			case 'settings_include_saved_sub': return 'Inkludera frågor du tidigare sparat';
			case 'settings_dark_mode': return 'Mörkt läge';
			case 'settings_dark_mode_sub': return 'Växla mellan ljust och mörkt tema';
			case 'settings_language': return 'Språk';
			case 'settings_language_sub': return 'Välj ditt föredragna språk';
			case 'settings_version': return 'Versionsinformation';
			case 'settings_app_version': return 'Appversion';
			case 'settings_commit': return 'Commit';
			case 'settings_branch': return 'Gren';
			case 'settings_last_update': return 'Senaste uppdatering';
			case 'settings_date': return 'Datum';
			case 'settings_saved': return 'Inställningar sparades';
			case 'profile_student': return 'STUDENT';
			case 'profile_edit': return 'Redigera profil';
			case 'profile_stats': return 'Mina resultat';
			case 'profile_settings': return 'Inställningar';
			case 'profile_invite': return 'Bjud in en vän';
			case 'profile_help': return 'Hjälp';
			case 'profile_logout_confirm': return 'Är du säker på att du vill logga ut?';
			case 'profile_yes_logout': return 'Ja, logga ut';
			case 'home_dashboard': return 'Instrumentpanel';
			case 'home_my_progress': return 'Min framsteg';
			case 'home_overall_score': return 'Totalt resultat';
			case 'home_passed': return 'Godkänd';
			case 'home_failed': return 'Underkänd';
			case 'home_total': return 'Totalt';
			case 'home_in_progress': return 'Pågående';
			case 'home_recent_activity': return 'Senaste aktivitet';
			case 'home_by_category': return 'Per kategori';
			case 'home_this_week': return 'Denna vecka';
			case 'home_this_month': return 'Denna månad';
			case 'home_no_attempts': return 'Inga försök än!';
			case 'home_no_attempts_sub': return 'När du slutfört ett prov visas dina resultat här.';
			case 'home_take_quiz': return 'Ta ditt första prov';
			case 'home_paused': return 'Pausad';
			case 'home_resume': return 'Återuppta';
			case 'home_attempts': return 'försök';
			case 'home_active': return 'aktiv';
			case 'home_tests': return 'prov';
			case 'intro_slide1_body': return 'Lär dig och öva inför ditt körkort enkelt.';
			case 'intro_slide2_title': return 'Interaktiva prov';
			case 'intro_slide2_body': return 'Övningsprov med direkt feedback och förklaringar.';
			case 'intro_slide3_title': return 'Bli godkänd';
			case 'intro_slide3_body': return 'Klara dina prov och bli en godkänd förare.';
			case 'intro_skip': return 'Hoppa över';
			case 'intro_get_started': return 'Kom igång';
			case 'auth_welcome_title': return 'Välkommen till Drive Test!';
			case 'auth_welcome_subtitle': return 'Öva. Klara prov tryggt.';
			case 'auth_login_btn': return 'LOGGA IN';
			case 'auth_signup_btn': return 'REGISTRERA';
			case 'auth_skip_demo': return 'HOPPA ÖVER (PROVA DEMO)';
			case 'auth_demo_error': return 'Kunde inte logga in med demokontot. Försök igen.';
			case 'auth_or': return 'ELLER';
			case 'auth_login_title': return 'Logga in';
			case 'auth_contact_support': return 'Kontakta support';
			case 'auth_username': return 'Användarnamn';
			case 'auth_email': return 'E-post';
			case 'auth_password': return 'Lösenord';
			case 'auth_remember_me': return 'Kom ihåg mig';
			case 'auth_forgot_password': return 'Glömt lösenord?';
			case 'auth_invalid_credentials': return 'Ogiltigt användarnamn eller lösenord';
			case 'auth_no_account': return 'Har du inget konto? ';
			case 'auth_sign_up_link': return 'Registrera dig';
			case 'auth_skip_demo_short': return 'Hoppa över (Prova demo)';
			case 'auth_google_continue': return 'Fortsätt med Google';
			case 'auth_feedback_type': return 'Typ';
			case 'auth_feedback_email_optional': return 'E-post (valfritt)';
			case 'auth_feedback_subject_optional': return 'Ämne (valfritt)';
			case 'auth_feedback_message': return 'Meddelande';
			case 'auth_feedback_sent': return 'Tack! Din feedback skickades.';
			case 'auth_feedback_error': return 'Kunde inte skicka feedback. Försök igen.';
			case 'auth_submit': return 'Skicka';
			case 'auth_feedback_login_issue': return 'Inloggningsproblem';
			case 'auth_feedback_signup_issue': return 'Registreringsproblem';
			case 'auth_feedback_app_issue': return 'Appproblem';
			case 'auth_feedback_feature_request': return 'Funktionsförfrågan';
			case 'auth_feedback_other': return 'Övrigt';
			case 'auth_create_account': return 'Skapa konto';
			case 'auth_sign_up_btn': return 'Registrera';
			case 'auth_val_username_required': return 'Vänligen ange ett användarnamn';
			case 'auth_val_username_length': return 'Användarnamnet måste vara minst 4 tecken';
			case 'auth_val_email_required': return 'Vänligen ange en e-postadress';
			case 'auth_val_email_invalid': return 'Vänligen ange en giltig e-postadress';
			case 'auth_val_password_required': return 'Vänligen ange ett lösenord';
			case 'auth_val_password_length': return 'Lösenordet måste vara minst 6 tecken';
			case 'auth_signup_success': return 'Registreringen lyckades! Vänligen logga in.';
			case 'auth_welcome_first_login': return 'Välkommen, lycka till!';
			case 'auth_welcome_returning': return 'Välkommen tillbaka igen!';
			case 'auth_deleted_account_welcome_back': return 'Alltid välkommen tillbaka.';
			case 'auth_signup_failed': return 'Registreringen misslyckades. Rätta felen.';
			case 'auth_generic_error': return 'Ett fel uppstod. Försök igen.';
			case 'auth_express_google': return 'Express-inloggning via Google';
			case 'auth_google_label': return 'Google';
			case 'auth_tab_login': return 'Logga in';
			case 'auth_tab_signup': return 'Registrera dig';
			case 'auth_show_password': return 'Visa';
			case 'auth_hide_password': return 'Dölj';
			case 'auth_forgot_title': return 'Glömt lösenord';
			case 'auth_forgot_heading': return 'Återställ ditt lösenord';
			case 'auth_forgot_subtitle': return 'Ange din e-postadress så skickar vi instruktioner för att återställa ditt lösenord.';
			case 'auth_forgot_email_label': return 'E-postadress';
			case 'auth_forgot_send_btn': return 'Skicka instruktioner';
			case 'auth_forgot_back_login': return 'Tillbaka till inloggning';
			case 'auth_forgot_success': return 'Instruktioner för lösenordsåterställning har skickats till din e-post.';
			case 'auth_forgot_error': return 'Det gick inte att skicka återställningsmail. Försök igen.';
			case 'purchase_success_title': return 'Ditt köp har\nbekräftats';
			case 'purchase_success_start_tests': return 'Starta prov';
			case 'purchase_success_back_home': return 'Tillbaka till start';
			case 'bcd_drive_test': return 'Drive Test';
			case 'bcd_exams': return 'Prov';
			case 'bcd_exams_sub': return 'Licenser, kategorier & prov';
			case 'bcd_traffic_signs': return 'Trafikskyltar';
			case 'bcd_traffic_signs_sub': return 'Bläddra bland alla trafikskyltar';
			case 'bcd_subscriptions': return 'Prenumerationer';
			case 'bcd_subscriptions_sub': return 'Visa planer och hantera åtkomst';
			case 'bcd_hub_practice': return 'Övning';
			case 'bcd_hub_tests': return 'Prov';
			case 'bcd_hub_theory_docs': return 'Teori-\ndokument';
			case 'bcd_hub_traffic_signs': return 'Trafikskyltar';
			case 'bcd_hub_checklist': return 'Checklista';
			case 'bcd_hub_statistics': return 'Statistik';
			case 'bcd_hub_saved_questions': return 'Sparade\nfrågor';
			case 'bcd_no_free_practice': return 'Inget gratis övningsprov tillgängligt för denna kategori.';
			case 'bcd_failed_practice': return 'Det gick inte att ladda övningsprovet.';
			case 'bcd_no_saved_questions': return 'Inga sparade frågor i denna kategori ännu.';
			case 'bcd_no_saved_questions_found': return 'Inga sparade frågor hittades i denna kategori.';
			case 'bcd_failed_saved': return 'Det gick inte att ladda sparade frågor.';
			case 'bcd_no_subscription': return 'Du har ingen aktiv prenumeration för denna kategori';
			case 'bcd_free_content_desc': return 'Övning, Trafikskyltar, Dokument och Checklistor är gratis. Prenumerera för att låsa upp Prov.';
			case 'bcd_buy_subscription': return 'Köp prenumeration';
			case 'bcd_buy_subscription_arrow': return 'Köp prenumeration →';
			case 'bcd_not_subscribed': return 'Du prenumererar inte på denna kategori';
			case 'bcd_only_free_tests': return 'Endast gratis övningsprov är tillgängliga. Prenumerera för att låsa upp alla prov.';
			case 'bcd_no_free_practice_tests': return 'Inga gratis övningsprov tillgängliga.';
			case 'bcd_no_tests': return 'Inga prov tillgängliga.';
			case 'bcd_no_documents': return 'Inga dokument tillgängliga.';
			case 'bcd_no_checklists': return 'Inga checklistor tillgängliga.';
			case 'bcd_failed_tests': return 'Det gick inte att ladda prov';
			case 'bcd_subscription_required': return 'Prenumeration krävs';
			case 'bcd_subscribe_access': return 'Prenumerera för att få tillgång till "{name}" och allt dess innehåll.';
			case 'bcd_not_now': return 'Inte nu';
			case 'bcd_buy': return 'Köp';
			case 'bcd_payment_failed': return 'Betalning misslyckades. Försök igen.';
			case 'bcd_feedback_unavailable': return 'Feedback ej tillgänglig för denna fråga.';
			case 'bcd_feedback_submitted': return 'Tack! Din feedback skickades.';
			case 'bcd_feedback_failed': return 'Kunde inte skicka feedback. Försök igen.';
			case 'bcd_categories': return 'Kategorier';
			case 'bcd_search_categories': return 'Sök kategorier…';
			case 'bcd_no_categories': return 'Inga kategorier tillgängliga.';
			case 'bcd_no_match_search': return 'Inga träffar hittades.';
			case 'bcd_subscribed': return 'Prenumererar';
			case 'bcd_tap_to_subscribe': return 'Tryck för att prenumerera';
			case 'bcd_failed_categories': return 'Det gick inte att ladda kategorier';
			case 'bcd_plans_tab': return 'Planer';
			case 'bcd_my_subscriptions_tab': return 'Mina prenumerationer';
			case 'bcd_no_plans': return 'Inga planer tillgängliga';
			case 'bcd_active_label': return 'Aktiv';
			case 'bcd_subscribe_btn': return 'Prenumerera';
			case 'bcd_no_active_subscriptions': return 'Inga aktiva prenumerationer';
			case 'bcd_browse_plans': return 'Bläddra bland planer för att komma igång';
			case 'bcd_expires': return 'Upphör';
			case 'bcd_failed_plans': return 'Det gick inte att ladda planer';
			case 'bcd_no_categories_linked': return 'Inga kategorier kopplade till den här prenumerationen';
			case 'bcd_failed_category': return 'Det gick inte att ladda kategorin';
			case 'bcd_search_signs': return 'Sök skyltgrupper…';
			case 'bcd_no_signs': return 'Inga skyltar hittades';
			case 'bcd_no_image': return 'Ingen bild';
			case 'bcd_signs_count_label': return 'trafikskyltar';
			case 'bcd_view': return 'Visa';
			case 'bcd_previous': return 'Föregående';
			case 'bcd_next': return 'Nästa';
			case 'bcd_failed_traffic_signs': return 'Det gick inte att ladda trafikskyltar';
			case 'bcd_search_hint': return 'Sök…';
			case 'bcd_no_subcategories': return 'Inga underkategorier tillgängliga.';
			case 'bcd_failed_subcategories': return 'Det gick inte att ladda underkategorier';
			case 'bcd_no_questions': return 'Inga frågor hittades för det här provet.';
			case 'bcd_failed_test_questions': return 'Det gick inte att ladda provfrågor.';
			case 'bcd_questions_label': return 'frågor';
			case 'bcd_pass_label': return 'Godkänt';
			case 'bcd_free_label': return 'GRATIS';
			default: return null;
		}
	}
}

